apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-wp-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 172.31.4.37
  share: /mnt/wordpress
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
