apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort  # Usa NodePort si tu proveedor no soporta LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
  selector:
    app: nginx-loadbalancer
