apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: csi-driver-nfs
  pass_credentials_all: false
  password: ""
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
  username: ""
